{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2", "trace": "self = <test.test_api.test_001.Test_login object at 0x00000129702FE518>\n\n    def test_002(self):\n>       assert 1==2\nE       assert 1 == 2\nE         -1\nE         +2\n\ntest_001.py:36: AssertionError"}, "start": 1617889053856, "stop": 1617889053857, "uuid": "f7fcdd80-e124-4000-9fa8-7f8b42d92de3", "historyId": "f9aeffe93ad42f98bd7e5471273ea75b", "testCaseId": "3798ceab0ddc293ff1d383a4d0f5d7fc", "fullName": "test.test_api.test_001.Test_login#test_002", "labels": [{"name": "parentSuite", "value": "test.test_api"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-5T9ABC0"}, {"name": "thread", "value": "20088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api.test_001"}]}