{"name": "test_006", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2", "trace": "self = <test.test_api.test_001.Test_login object at 0x00000129702D06D8>\n\n    def test_006(self):\n>       assert 1==2\nE       assert 1 == 2\nE         -1\nE         +2\n\ntest_001.py:32: AssertionError"}, "start": 1617889053710, "stop": 1617889053710, "uuid": "96508d62-bbf4-4a18-9d4f-6c7ef1b79a76", "historyId": "433b27c31acfab2f921d28d98394920c", "testCaseId": "612c6475a29b6e53f91c43e4aba8421f", "fullName": "test.test_api.test_001.Test_login#test_006", "labels": [{"name": "parentSuite", "value": "test.test_api"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-5T9ABC0"}, {"name": "thread", "value": "20088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api.test_001"}]}