{"name": "test_003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2", "trace": "self = <test.test_api.test_001.Test_login object at 0x0000012970362128>\n\n    def test_003(self):\n>       assert 1==2\nE       assert 1 == 2\nE         -1\nE         +2\n\ntest_001.py:39: AssertionError"}, "start": 1617889053869, "stop": 1617889053869, "uuid": "bbee2f31-7796-42d0-860f-63c87a0dca79", "historyId": "ba1300e13436d95999db4e6ba5e71025", "testCaseId": "975549612c7aa4516dd58f25e6d82a0b", "fullName": "test.test_api.test_001.Test_login#test_003", "labels": [{"name": "parentSuite", "value": "test.test_api"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-5T9ABC0"}, {"name": "thread", "value": "20088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api.test_001"}]}